### ISSUE TITLE
Missing info about React 0.60 and Android setup

### ISSUE THREAD

**Issue by dbeff** [MicrosoftDocs/appcenter-docs#625] opened 2019-07-10 10:30 UTC
Please keep in mind that the command `react-native link` is not supported in the new version of React Native (0.60). It's a very recent version and with a very important change called autolinking. The documentation should also include caveats of use link after version 0.60 of react native.
https://facebook.github.io/react-native/blog/2019/07/03/version-60#native-modules-are-now-autolinked

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed0fde7-9e78-c318-9f8c-9d921ec7d7b3
* Version Independent ID: 946ead1c-4b65-8318-c77a-ef98873adac7
* Content: [Get Started with React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#feedback)
* Content Source: [docs/sdk/getting-started/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **elamalani**

**Comment by jwargo** [comment] 2019-07-11 16:43
duplicate of #617

**Closed as completed by jwargo** 2019-07-11 16:43 UTC
