### ISSUE TITLE
Missing blue chat button

### ISSUE THREAD

**Issue by apple-ihack-geek** [MicrosoftDocs/appcenter-docs#693] opened 2019-08-28 12:29 UTC
"To get help on any issue you may experience, use the blue chat button at the bottom-right corner of every App Center portal page"
Yet on every app center page I can see, there is no blue chat button.  Why is this? I even tried turning off all my ad and content blockers but I still don't see any blue chat button. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45dd71a0-a249-a87b-e4eb-e4da0a20472f
* Version Independent ID: 450c26f5-ab13-8df5-d45a-6086f5391b23
* Content: [App Center Support - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/support-center#feedback)
* Content Source: [docs/general/support-center.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/support-center.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by blparr** [comment] 2019-08-29 02:05
Hello @apple-ihack-geek ! This could be due to an ad-blocker. Can you try disabling those?

Thanks!

**Comment by apple-ihack-geek** [comment] 2019-08-29 12:14
@blparr  That was my first thought as well, which is why as I indicated in my first message, I tried turning all of them off and refreshing the page.

**Comment by blparr** [comment] 2019-08-30 18:16
Oh sorry I totally missed that part! Let me chat with the team and get back to you as soon as I have an update for you.

**Comment by blparr** [comment] 2019-08-30 20:06
Could you please confirm your OS version + Browser version?

Thank you!

**Comment by apple-ihack-geek** [comment] 2019-08-30 20:07
Mac os 10.13.6 Safari 11.1.2.  I forget but I may also have tried in chrome.

—Benjamin Kier

On Aug 30, 2019, at 4:06 PM, Blanca Delgado Parra <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you please confirm your OS version + Browser version?

Thank you!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fappcenter-docs%2Fissues%2F693%3Femail_source%3Dnotifications%26email_token%3DABKU4GOQALDTYYYZPULRNR3QHF4TDA5CNFSM4IRFKPC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5SUT3Y%23issuecomment-526731759&data=02%7C01%7Cbenjamin.kier%40legrand.com%7C9aa7590032334a5d0d5208d72d858062%7C199686b5bef4496087867a6b1888fee3%7C1%7C0%7C637027923715901733&sdata=E%2Bg7gDte0%2BHLdk3eUIilzsfnYxvRCxT%2BLxxHhgmPbzY%3D&reserved=0>, or mute the thread<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABKU4GM74IMJK77KZMQCUM3QHF4TDANCNFSM4IRFKPCQ&data=02%7C01%7Cbenjamin.kier%40legrand.com%7C9aa7590032334a5d0d5208d72d858062%7C199686b5bef4496087867a6b1888fee3%7C1%7C0%7C637027923715911721&sdata=DhxTsOx3NdKfM4JYAys8giqX71rJSyAjIrN%2BgInbtwM%3D&reserved=0>.


________________________________

Ce message, ainsi que tous les fichiers joints à ce message, peuvent contenir des informations sensibles et/ ou confidentielles ne devant pas être divulguées. Si vous n'êtes pas le destinataire de ce message (ou que vous recevez ce message par erreur), nous vous remercions de le notifier immédiatement à son expéditeur, et de détruire ce message. Toute copie, divulgation, modification, utilisation ou diffusion, non autorisée, directe ou indirecte, de tout ou partie de ce message, est strictement interdite.


This e-mail, and any document attached hereby, may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized, direct or indirect, copying, disclosure, distribution or other use of the material or parts thereof is strictly forbidden.

**Comment by blparr** [comment] 2019-08-30 22:55
Hello! Thanks for sending that over. It looks like we are unable to reproduce your issue. The team would like to ask you a few additional questions. Would you mind sending us an email at support@appcenter.ms with a link to this issue?

Thank you!

**Comment by blparr** [comment] 2019-08-30 23:01
I'll close this issue here, but feel free to re-open if you don't get this solved via the support email.

**Closed as completed by blparr** 2019-08-30 23:01 UTC

**Comment by jpc1963** [comment] 2019-09-09 11:03
I have this problem now. tested with chrome / firefox on my mac. and firefox on my pc.
A few days ago I had no problem with the chat.

**Comment by blparr** [comment] 2019-09-09 21:38
Hi @jpc1963 , thanks for reporting this. We are having a hard time reproducing this issue, if you could reach out to us via support@appcenter.ms we will to look into it further.

Thanks!
