### ISSUE TITLE
Support email is invalid

### ISSUE THREAD

**Issue by millyvanilly** [MicrosoftDocs/appcenter-docs#1487] opened 2023-12-08 03:29 UTC
Tried reaching out to you about your services being down, your email bounced back 
![image](https://github.com/MicrosoftDocs/appcenter-docs/assets/5965362/383f0d3a-24c1-428d-bbf0-cc5f888ecca2)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36da5026-39aa-9a48-440c-7e57da3e3373
* Version Independent ID: eff2f79f-df52-829f-a0c3-71396e365884
* Content: [Help and Feedback - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/help)
* Content Source: [docs/help.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/help.md)
* Service: **vs-appcenter**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by lucen-ms** [comment] 2023-12-18 08:54
duplicate of #1483

**Closed as completed by lucen-ms** 2023-12-18 08:54 UTC
Labels: vs-appcenter/svc, Pri1
