### ISSUE TITLE
Email address support@appcenter.ms undeliverable

### ISSUE THREAD

**Issue by farmerpaul** [MicrosoftDocs/appcenter-docs#1484] opened 2023-12-08 00:54 UTC
I can't access https://appcenter.ms because the site is down, so I can't access support through the normal means. Your [support page](https://twitter.com/AppCenterStatus) says I can email support@appcenter.ms to report the issue, but doing so bounces with this:

<img width="1096" alt="Screenshot 2023-12-07 at 8 43 37 PM" src="https://github.com/MicrosoftDocs/appcenter-docs/assets/1282772/fbc38505-c492-46ba-87f9-4ded573e061e">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36da5026-39aa-9a48-440c-7e57da3e3373
* Version Independent ID: eff2f79f-df52-829f-a0c3-71396e365884
* Content: [Help and Feedback - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/help)
* Content Source: [docs/help.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/help.md)
* Service: **vs-appcenter**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by Adam-Langley** [comment] 2023-12-08 01:59
Same here. Appcenter is down (has been for over an hour), appcenter status page doesnt list any issues. Nothing listed on twitter. Socks up guys.

**Comment by lucen-ms** [comment] 2023-12-18 08:53
duplicate of #1483

**Closed as completed by lucen-ms** 2023-12-18 08:53 UTC
Labels: vs-appcenter/svc, Pri1
