### ISSUE TITLE
Unable to modify notification settings

### ISSUE THREAD

**Issue by pronouncedJerry** [MicrosoftDocs/appcenter-docs#1214] opened 2021-03-23 12:26 UTC
How come I can no longer fine tune the types of notifications as stated in this documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e1cc1d-912c-61a7-04b3-1215b1d2e3a8
* Version Independent ID: 6fdf262f-0133-8ffb-81a6-fd24eb1a3b8e
* Content: [App Center Email Notifications Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/email-notifications/#email-notification-preferences)
* Content Source: [docs/dashboard/email-notifications/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/email-notifications/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by DmitriyKirakosyan** [comment] 2021-03-31 22:23
Duplicate of https://github.com/MicrosoftDocs/appcenter-docs/issues/1191

**Closed as completed by DmitriyKirakosyan** 2021-03-31 22:23 UTC
Labels: Support Question, vs-appcenter/svc, Pri1, app-center-general/subsvc, App Center Alerting
