### ISSUE TITLE
Instructions are wrong for per-app email settings

### ISSUE THREAD

**Issue by slambert-msft** [MicrosoftDocs/appcenter-docs#1198] opened 2021-02-17 02:18 UTC
I followed the "Manage your notification settings" link from some annoying spam about iOS Dogfood apps (I don't even have iOS) and got to these instructions.  They suggest going to https://appcenter.ms/apps, selecting an app, and then in the settings from the left, changing the email settings.  However, when I select an app all I get is a modal QR Code pop-up.  I can't even open the menu on the left unless I dismiss the QR Code, and when I do there is no settings option available.

I was, however, able to simply block all email from appcenter, so that part of the instructions seems fine.  Given that there are over 150 iOS apps listed, it was unlikely that I would bother going to each one of them and telling them to leave me alone anyway.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e1cc1d-912c-61a7-04b3-1215b1d2e3a8
* Version Independent ID: 6fdf262f-0133-8ffb-81a6-fd24eb1a3b8e
* Content: [App Center Email Notifications Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/email-notifications/#email-notification-preferences)
* Content Source: [docs/dashboard/email-notifications/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/email-notifications/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by DmitriyKirakosyan** [comment] 2021-03-31 22:22
Duplicate of https://github.com/MicrosoftDocs/appcenter-docs/issues/1191

**Closed as completed by DmitriyKirakosyan** 2021-03-31 22:22 UTC
Labels: App Center Accounts, vs-appcenter/svc, Pri1, app-center-general/subsvc
