### ISSUE TITLE
Telemetry support for UWP app with C++/WinRT

### ISSUE THREAD

**Issue by amwate** [MicrosoftDocs/appcenter-docs#1322] opened 2021-12-28 14:42 UTC
Any workaround or partial support for Telemetry with C++-based UWP would be great. I didn't find any C++-based SDK for the app center support. 
This is almost the same as https://github.com/MicrosoftDocs/appcenter-docs/issues/576 but has a single feature request.

**Comment by AnatolyPristensky** [comment] 2021-12-29 07:44
Hello @amwate and thank you for getting in touch with us!

As AppCenter SDK is developing as a complex solution (e.g Analytics, Crashes, Distribute) - we can't implement only one of these modules, so I'm closing this one as a duplicate of #576. 

Currently support of C++ based apps isn't on our roadmap.

> Workaround or partial support for Telemetry with C++-based UWP would be great. I didn't find any C++-based SDK for the app center support.

You can create a common UWP app on the App Center portal and try to send telemetry from your C++ based app. Even though this approach may work for you, it is not officially supported. Also note, that in this case you need to implement a custom C++ SDK that will send the data.

**Closed as completed by AnatolyPristensky** 2021-12-29 07:44 UTC
Labels: App Center SDK, Pri3
