### ISSUE TITLE
starting AppCenter in application's constructor throws InvalidOperationException.

### ISSUE THREAD

**Issue by HppZ** [MicrosoftDocs/appcenter-docs#1275] opened 2021-08-05 09:37 UTC
starting AppCenter in application's constructor throws InvalidOperationException, so should I call AppCenter.Start in `OnLaunched(LaunchActivatedEventArgs e)` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ece9ab-9965-2ddf-34b6-44f0f61fe599
* Version Independent ID: 16261b98-a85e-060f-ccf4-3a24f5f14c4c
* Content: [Get Started with UWP - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/uwp)
* Content Source: [docs/sdk/getting-started/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/uwp.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by HppZ** [comment] 2021-08-05 09:37
https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/uwp
![image](https://user-images.githubusercontent.com/12285582/128328577-19cb27f6-9db7-45f4-8853-39329f62efff.png)

**Comment by DmitriyKirakosyan** [comment] 2021-08-15 15:21
Hi @HppZ 

Thank  you for reaching out to us!

AppCenter SDK should start successfully if you call `AppCenter.Start` in App constructor.

Could you clarify what version of AppCenter SDK you are using?
What version of windows sdk are you targeting?
Can you reproduce the issue on a blank application?
Please turn on verbose logging by calling `AppCenter.LogLevel = LogLevel.Verbose` before starting the SDK, and share the logs with us.

**Comment by HppZ** [comment] 2021-08-17 05:54
@DmitriyKirakosyan repro https://github.com/HppZ/TestAppCenterStart

**Comment by HppZ** [comment] 2021-08-17 05:54
![image](https://user-images.githubusercontent.com/12285582/129671077-959434a4-a339-4a62-9dd1-c058af8f203a.png)

**Comment by HppZ** [comment] 2021-08-18 07:48
any idea? @DmitriyKirakosyan

**Comment by HppZ** [comment] 2021-08-18 07:50
AppCenter 4.3.0
minVersion 16299
targetVersion 17763

**Comment by AnastasiaKubova** [comment] 2021-08-18 10:38
Hello @HppZ ! Thanks for sharing the sample app. I checked it but for me all work well. Could you please share the verbose logs?

**Comment by HppZ** [comment] 2021-08-18 10:43
Exception thrown: 'System.InvalidOperationException' in Microsoft.AppCenter.dll
WinRT information: Could not create a new view because the main window has not yet been created
2021-08-18 18:43:10.457 [AppCenter] DEBUG: Not invoking resume immediately because UI is not ready.
2021-08-18 18:43:10.694 [AppCenter] DEBUG: No named identifier found in appSecret; using as-is
2021-08-18 18:43:10.907 [AppCenter] DEBUG: Creating database at: C:\Users\haopeng\AppData\Local\Packages\866e6f01-1db0-4460-a5f7-ee098eebda55_kmdshx21vdgze\LocalState\Microsoft.AppCenter.Storage
2021-08-18 18:43:10.914 [AppCenter] DEBUG: AddChannel(core)
2021-08-18 18:43:11.001 [AppCenter] INFO: App Center SDK configured successfully.
2021-08-18 18:43:11.003 [AppCenter] DEBUG: Set max storage size.
2021-08-18 18:43:11.008 [AppCenter] DEBUG: AddChannel(analytics)
2021-08-18 18:43:11.014 [AppCenter] INFO: Found 3 pages in the database.
2021-08-18 18:43:11.024 [AppCenter] INFO: Changed maximum database size to 10485760 bytes.
2021-08-18 18:43:11.029 [AppCenter] INFO: 'Analytics' service started.
2021-08-18 18:43:11.035 [AppCenter] DEBUG: AddChannel(crashes)
2021-08-18 18:43:11.042 [AppCenter] INFO: 'Crashes' service started.
2021-08-18 18:43:11.049 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'core'
2021-08-18 18:43:11.908 [AppCenterAnalytics] DEBUG: SessionTracker.Resume
2021-08-18 18:43:11.911 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'analytics'
2021-08-18 18:43:11.987 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'analytics'
2021-08-18 18:43:11.989 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'core'
2021-08-18 18:43:12.531 [AppCenter] DEBUG: CheckPendingLogs(core) pending log count: 2
2021-08-18 18:43:12.541 [AppCenter] DEBUG: CheckPendingLogs(analytics) pending log count: 2
2021-08-18 18:43:15.551 [AppCenter] DEBUG: TriggerIngestion(core) pending log count: 2
2021-08-18 18:43:15.553 [AppCenter] DEBUG: TriggerIngestion(analytics) pending log count: 2
2021-08-18 18:43:15.557 [AppCenter] DEBUG: Trying to get up to 50 logs from storage for core
2021-08-18 18:43:15.658 [AppCenter] DEBUG: The SID/ID pairs for returning logs are:
	(null) / 1
	(null) / 3
2021-08-18 18:43:15.659 [AppCenter] DEBUG: Trying to get up to 50 logs from storage for analytics
2021-08-18 18:43:15.661 [AppCenter] DEBUG: Invoke SendingLog event for channel 'core'
2021-08-18 18:43:15.663 [AppCenter] DEBUG: Invoke SendingLog event for channel 'core'
2021-08-18 18:43:15.669 [AppCenter] DEBUG: The SID/ID pairs for returning logs are:
	bebcca2a-bdc8-4e59-bab5-ec1b5f924277 / 2
	3fd24d37-a889-4041-850a-06a78ccb91b4 / 4
2021-08-18 18:43:15.671 [AppCenter] DEBUG: Invoke SendingLog event for channel 'analytics'
2021-08-18 18:43:15.683 [AppCenter] DEBUG: Invoke SendingLog event for channel 'analytics'
2021-08-18 18:43:15.698 [AppCenter] VERBOSE: Calling https://in.appcenter.ms/logs?api-version=1.0.0...
2021-08-18 18:43:15.699 [AppCenter] VERBOSE: Calling https://in.appcenter.ms/logs?api-version=1.0.0...
2021-08-18 18:43:15.702 [AppCenter] VERBOSE: Headers: App-Secret=****************************acc060ac, Install-ID=c6cf8e94-ca39-4b51-a4c4-ae35b673d4e3
2021-08-18 18:43:15.703 [AppCenter] VERBOSE: Headers: App-Secret=****************************acc060ac, Install-ID=c6cf8e94-ca39-4b51-a4c4-ae35b673d4e3
2021-08-18 18:43:15.705 [AppCenter] VERBOSE: {
  "logs": [
    {
  "services": [
    "Analytics",
    "Crashes"
  ],
  "timestamp": "2021-08-17T05:50:47.2297044Z",
  "device": {
    "sdkName": "appcenter.uwp",
    "sdkVersion": "4.3.0",
    "model": "HP EliteDesk 800 G5 TWR",
    "oemName": "HP",
    "osName": "WINDOWS",
    "osVersion": "10.0.19042",
    "osBuild": "10.0.19042.985",
    "locale": "en-US",
    "timeZoneOffset": 480,
    "appVersion": "1.0.0.0",
    "appBuild": "1.0.0.0",
    "appNamespace": "866e6f01-1db0-4460-a5f7-ee098eebda55"
  },
  "type": "startService"
},
    {
  "services": [
    "Analytics",
    "Crashes"
  ],
  "timestamp": "2021-08-18T10:43:11.9871214Z",
  "device": {
    "sdkName": "appcenter.uwp",
    "sdkVersion": "4.3.0",
    "model": "HP EliteDesk 800 G5 TWR",
    "oemName": "HP",
    "osName": "WINDOWS",
    "osVersion": "10.0.19042",
    "osBuild": "10.0.19042.985",
    "locale": "en-US",
    "timeZoneOffset": 480,
    "screenSize": "1920x1080",
    "appVersion": "1.0.0.0",
    "appBuild": "1.0.0.0",
    "appNamespace": "866e6f01-1db0-4460-a5f7-ee098eebda55"
  },
  "type": "startService"
}
  ]
}
2021-08-18 18:43:15.707 [AppCenter] VERBOSE: {
  "logs": [
    {
  "timestamp": "2021-08-17T05:50:48.521131Z",
  "sid": "bebcca2a-bdc8-4e59-bab5-ec1b5f924277",
  "device": {
    "sdkName": "appcenter.uwp",
    "sdkVersion": "4.3.0",
    "model": "HP EliteDesk 800 G5 TWR",
    "oemName": "HP",
    "osName": "WINDOWS",
    "osVersion": "10.0.19042",
    "osBuild": "10.0.19042.985",
    "locale": "en-US",
    "timeZoneOffset": 480,
    "appVersion": "1.0.0.0",
    "appBuild": "1.0.0.0",
    "appNamespace": "866e6f01-1db0-4460-a5f7-ee098eebda55"
  },
  "type": "startSession"
},
    {
  "timestamp": "2021-08-18T10:43:11.9871221Z",
  "sid": "3fd24d37-a889-4041-850a-06a78ccb91b4",
  "device": {
    "sdkName": "appcenter.uwp",
    "sdkVersion": "4.3.0",
    "model": "HP EliteDesk 800 G5 TWR",
    "oemName": "HP",
    "osName": "WINDOWS",
    "osVersion": "10.0.19042",
    "osBuild": "10.0.19042.985",
    "locale": "en-US",
    "timeZoneOffset": 480,
    "screenSize": "1920x1080",
    "appVersion": "1.0.0.0",
    "appBuild": "1.0.0.0",
    "appNamespace": "866e6f01-1db0-4460-a5f7-ee098eebda55"
  },
  "type": "startSession"
}
  ]
}
2021-08-18 18:43:17.158 [AppCenter] DEBUG: CheckPendingLogs(core) pending log count: 0
2021-08-18 18:43:17.160 [AppCenter] DEBUG: CheckPendingLogs(analytics) pending log count: 0
2021-08-18 18:43:18.566 [AppCenter] VERBOSE: HTTP response status=401 (Unauthorized) payload={"status":"AppSecretDenied","validDiagnosticsIds":[],"throttledDiagnosticsIds":[],"correlationId":"459fd19f-cd3f-47e3-998e-9b439925d903"}
2021-08-18 18:43:18.568 [AppCenter] VERBOSE: HTTP response status=401 (Unauthorized) payload={"status":"AppSecretDenied","validDiagnosticsIds":[],"throttledDiagnosticsIds":[],"correlationId":"44b78648-196b-43f2-8f3a-02029454d1ce"}
Exception thrown: 'Microsoft.AppCenter.Ingestion.Http.HttpIngestionException' in Microsoft.AppCenter.dll
Exception thrown: 'Microsoft.AppCenter.Ingestion.Http.HttpIngestionException' in Microsoft.AppCenter.dll
Exception thrown: 'Microsoft.AppCenter.Ingestion.Http.HttpIngestionException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.AppCenter.Ingestion.Http.HttpIngestionException' in System.Private.CoreLib.dll
2021-08-18 18:43:18.739 [AppCenter] ERROR: Sending logs for channel 'analytics', batch '2fb376c1-c2c3-4ddf-a4ab-5dadfd1d46c9' failed: Microsoft.AppCenter.Ingestion.Http.HttpIngestionException: HTTP response status=401 (Unauthorized) payload={"status":"AppSecretDenied","validDiagnosticsIds":[],"throttledDiagnosticsIds":[],"correlationId":"459fd19f-cd3f-47e3-998e-9b439925d903"}
   at Microsoft.AppCenter.Ingestion.Http.HttpNetworkAdapter.SendAsync(String uri, String method, IDictionary`2 headers, String jsonContent, CancellationToken cancellationToken)
   at Microsoft.AppCenter.Ingestion.Http.IngestionHttp.CallAsync(String appSecret, Guid installId, IList`1 logs, CancellationToken token)
2021-08-18 18:43:18.741 [AppCenter] ERROR: Sending logs for channel 'core', batch 'c1bd0d73-598e-4cfb-bbbf-a0bca2af2606' failed: Microsoft.AppCenter.Ingestion.Http.HttpIngestionException: HTTP response status=401 (Unauthorized) payload={"status":"AppSecretDenied","validDiagnosticsIds":[],"throttledDiagnosticsIds":[],"correlationId":"44b78648-196b-43f2-8f3a-02029454d1ce"}
   at Microsoft.AppCenter.Ingestion.Http.HttpNetworkAdapter.SendAsync(String uri, String method, IDictionary`2 headers, String jsonContent, CancellationToken cancellationToken)
   at Microsoft.AppCenter.Ingestion.Http.IngestionHttp.CallAsync(String appSecret, Guid installId, IList`1 logs, CancellationToken token)
2021-08-18 18:43:18.743 [AppCenter] DEBUG: Invoke FailedToSendLog event for channel 'analytics'
2021-08-18 18:43:18.744 [AppCenter] DEBUG: Invoke FailedToSendLog event for channel 'core'
2021-08-18 18:43:18.746 [AppCenter] DEBUG: Invoke FailedToSendLog event for channel 'analytics'
2021-08-18 18:43:18.747 [AppCenter] DEBUG: Invoke FailedToSendLog event for channel 'core'
2021-08-18 18:43:18.749 [AppCenter] DEBUG: Deleting logs from storage for channel 'analytics' with batch id '2fb376c1-c2c3-4ddf-a4ab-5dadfd1d46c9'
2021-08-18 18:43:18.751 [AppCenter] DEBUG: Suspend channel: 'analytics'
2021-08-18 18:43:18.753 [AppCenter] DEBUG: Suspend channel: 'core'
2021-08-18 18:43:18.755 [AppCenter] DEBUG: The IDs for deleting log(s) is/are:
	2
	4
2021-08-18 18:43:18.766 [AppCenter] DEBUG: Deleting logs from storage for channel 'core' with batch id 'c1bd0d73-598e-4cfb-bbbf-a0bca2af2606'
2021-08-18 18:43:18.768 [AppCenter] DEBUG: The IDs for deleting log(s) is/are:
	1
	3
2021-08-18 18:43:18.779 [AppCenter] DEBUG: Trying to get up to 100 logs from storage for core
2021-08-18 18:43:18.780 [AppCenter] DEBUG: No available logs in storage for channel 'core'
2021-08-18 18:43:18.783 [AppCenter] DEBUG: Trying to get up to 100 logs from storage for analytics
2021-08-18 18:43:18.785 [AppCenter] DEBUG: No available logs in storage for channel 'analytics'
2021-08-18 18:43:18.788 [AppCenter] DEBUG: Clear pending log states for channel core
2021-08-18 18:43:18.790 [AppCenter] DEBUG: Clear pending log states for channel analytics
2021-08-18 18:43:18.792 [AppCenter] DEBUG: Deleting all logs from storage for channel 'core'
2021-08-18 18:43:18.794 [AppCenter] DEBUG: Deleting all logs from storage for channel 'analytics'

**Comment by AnastasiaKubova** [comment] 2021-08-18 12:07
Thanks for the details. Based on your logs I see that App Center was configured and start successfully but looks like you use the wrong app secret. Please make sure that you insert the right app secret.

**Comment by HppZ** [comment] 2021-08-18 12:10
No, it is correct secret in my real app. and that log was from my real app.
secret in that demo app is not real.

**Comment by AnastasiaKubova** [comment] 2021-08-18 12:13
Based on your logs above you use the wrong app secret:
`HTTP response status=401 (Unauthorized) payload={"status":"AppSecretDenied","validDiagnosticsIds":[],"throttledDiagnosticsIds":[],"correlationId":"44b78648-196b-43f2-8f3a-02029454d1ce"}`

**Comment by HppZ** [comment] 2021-08-18 12:15
my mistake, wait I will post a new one.

**Comment by HppZ** [comment] 2021-08-18 12:19
Exception thrown: 'System.InvalidOperationException' in Microsoft.AppCenter.dll
2021-08-18 20:17:27.044 [AppCenter] DEBUG: Not invoking resume immediately because UI is not ready.
2021-08-18 20:17:27.345 [AppCenter] DEBUG: No named identifier found in appSecret; using as-is
2021-08-18 20:17:27.939 [AppCenter] DEBUG: Creating database at: C:\Users\haopeng\AppData\Local\Packages\36699Atelier39.forWin102_pke1vz55rvc1r\LocalState\Microsoft.AppCenter.Storage
2021-08-18 20:17:27.972 [AppCenter] DEBUG: AddChannel(core)
2021-08-18 20:17:28.233 [AppCenter] INFO: App Center SDK configured successfully.
2021-08-18 20:17:28.264 [AppCenter] DEBUG: Set max storage size.
2021-08-18 20:17:28.296 [AppCenter] DEBUG: AddChannel(analytics)
2021-08-18 20:17:28.329 [AppCenter] INFO: Found 577 pages in the database.
2021-08-18 20:17:28.359 [AppCenter] INFO: Changed maximum database size to 10485760 bytes.
2021-08-18 20:17:28.391 [AppCenter] INFO: 'Analytics' service started.
2021-08-18 20:17:28.424 [AppCenter] DEBUG: AddChannel(crashes)
2021-08-18 20:17:28.454 [AppCenter] INFO: 'Crashes' service started.
2021-08-18 20:17:28.489 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'core'
2021-08-18 20:17:31.631 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'core'
2021-08-18 20:17:34.198 [AppCenter] DEBUG: CheckPendingLogs(core) pending log count: 1
2021-08-18 20:17:35.609 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'analytics'
2021-08-18 20:17:35.647 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'analytics'
2021-08-18 20:17:35.853 [AppCenter] DEBUG: CheckPendingLogs(analytics) pending log count: 1
2021-08-18 20:17:36.458 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'analytics'
2021-08-18 20:17:36.488 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'analytics'
2021-08-18 20:17:36.562 [AppCenter] DEBUG: CheckPendingLogs(analytics) pending log count: 2
2021-08-18 20:17:36.601 [AppCenterAnalytics] DEBUG: SessionTracker.Resume
2021-08-18 20:17:36.633 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'analytics'
2021-08-18 20:17:36.663 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'analytics'
2021-08-18 20:17:36.742 [AppCenter] DEBUG: CheckPendingLogs(analytics) pending log count: 3
2021-08-18 20:17:37.393 [AppCenter] DEBUG: TriggerIngestion(core) pending log count: 1
2021-08-18 20:17:37.493 [AppCenter] DEBUG: Trying to get up to 50 logs from storage for core
2021-08-18 20:17:38.295 [AppCenter] DEBUG: The SID/ID pairs for returning logs are:
	(null) / 1176
2021-08-18 20:17:38.308 [AppCenter] DEBUG: Invoke SendingLog event for channel 'core'
2021-08-18 20:17:38.554 [AppCenter] VERBOSE: Calling https://in.appcenter.ms/logs?api-version=1.0.0...
2021-08-18 20:17:38.594 [AppCenter] VERBOSE: Headers: App-Secret=****************************acc060ac, Install-ID=fa1fcd50-e107-45c2-8c75-86686dacca15
2021-08-18 20:17:38.627 [AppCenter] VERBOSE: {
  "logs": [
    {
  "services": [
    "Analytics",
    "Crashes"
  ],
  "timestamp": "2021-08-18T12:17:31.6304595Z",
  "device": {
    "sdkName": "appcenter.uwp",
    "sdkVersion": "4.3.0",
    "model": "HP EliteDesk 800 G5 TWR",
    "oemName": "HP",
    "osName": "WINDOWS",
    "osVersion": "10.0.19042",
    "osBuild": "10.0.19042.985",
    "locale": "en-US",
    "timeZoneOffset": 480,
    "appVersion": "2.14.28.0",
    "appBuild": "2.14.28.0",
    "appNamespace": "36699Atelier39.forWin102"
  },
  "type": "startService"
}
  ]
}
Handling new window size: 1171x932
2021-08-18 20:17:39.157 [AppCenter] DEBUG: TriggerIngestion(analytics) pending log count: 3
2021-08-18 20:17:39.192 [AppCenter] DEBUG: Trying to get up to 50 logs from storage for analytics
2021-08-18 20:17:39.228 [AppCenter] DEBUG: CheckPendingLogs(core) pending log count: 0
2021-08-18 20:17:39.335 [AppCenter] DEBUG: The SID/ID pairs for returning logs are:
	(null) / 1177
	(null) / 1178
	5ed1d909-d97b-4cf1-ab1e-180d2b41cdeb / 1179
2021-08-18 20:17:39.365 [AppCenter] DEBUG: Invoke SendingLog event for channel 'analytics'
2021-08-18 20:17:39.397 [AppCenter] DEBUG: Invoke SendingLog event for channel 'analytics'
2021-08-18 20:17:39.400 [AppCenter] DEBUG: Invoke SendingLog event for channel 'analytics'
2021-08-18 20:17:39.408 [AppCenter] VERBOSE: Calling https://in.appcenter.ms/logs?api-version=1.0.0...
2021-08-18 20:17:39.443 [AppCenter] VERBOSE: Headers: App-Secret=****************************acc060ac, Install-ID=fa1fcd50-e107-45c2-8c75-86686dacca15
2021-08-18 20:17:39.474 [AppCenter] VERBOSE: {
  "logs": [
    {
  "id": "2988fbc3-fafe-4491-99e5-194edc764ea1",
  "name": "app.active.startup.sys",
  "properties": {
    "kind": "app-ctor",
    "pre_state": "app-ctor"
  },
  "timestamp": "2021-08-18T12:17:35.6479866Z",
  "device": {
    "sdkName": "appcenter.uwp",
    "sdkVersion": "4.3.0",
    "model": "HP EliteDesk 800 G5 TWR",
    "oemName": "HP",
    "osName": "WINDOWS",
    "osVersion": "10.0.19042",
    "osBuild": "10.0.19042.985",
    "locale": "en-US",
    "timeZoneOffset": 480,
    "appVersion": "2.14.28.0",
    "appBuild": "2.14.28.0",
    "appNamespace": "36699Atelier39.forWin102"
  },
  "type": "event"
},
    {
  "id": "b5ac740d-364f-4fdb-bbcf-00458e6f7f4d",
  "name": "app.active.startup.sys",
  "properties": {
    "kind": "Launch",
    "pre_state": "Terminated"
  },
  "timestamp": "2021-08-18T12:17:36.4882684Z",
  "device": {
    "sdkName": "appcenter.uwp",
    "sdkVersion": "4.3.0",
    "model": "HP EliteDesk 800 G5 TWR",
    "oemName": "HP",
    "osName": "WINDOWS",
    "osVersion": "10.0.19042",
    "osBuild": "10.0.19042.985",
    "locale": "en-US",
    "timeZoneOffset": 480,
    "appVersion": "2.14.28.0",
    "appBuild": "2.14.28.0",
    "appNamespace": "36699Atelier39.forWin102"
  },
  "type": "event"
},
    {
  "timestamp": "2021-08-18T12:17:36.6634274Z",
  "sid": "5ed1d909-d97b-4cf1-ab1e-180d2b41cdeb",
  "device": {
    "sdkName": "appcenter.uwp",
    "sdkVersion": "4.3.0",
    "model": "HP EliteDesk 800 G5 TWR",
    "oemName": "HP",
    "osName": "WINDOWS",
    "osVersion": "10.0.19042",
    "osBuild": "10.0.19042.985",
    "locale": "en-US",
    "timeZoneOffset": 480,
    "appVersion": "2.14.28.0",
    "appBuild": "2.14.28.0",
    "appNamespace": "36699Atelier39.forWin102"
  },
  "type": "startSession"
}
  ]
}
2021-08-18 20:17:39.505 [AppCenter] DEBUG: CheckPendingLogs(analytics) pending log count: 0

**Comment by HppZ** [comment] 2021-08-18 12:20
Exception thrown: 'System.InvalidOperationException' in Microsoft.AppCenter.dll
2021-08-18 20:17:27.044 [AppCenter] DEBUG: Not invoking resume immediately because UI is not ready.
2021-08-18 20:17:27.345 [AppCenter] DEBUG: No named identifier found in appSecret; using as-is
2021-08-18 20:17:27.939 [AppCenter] DEBUG: Creating database at: C:\Users\haopeng\AppData\Local\Packages\APPNAMEDELETED\LocalState\Microsoft.AppCenter.Storage
2021-08-18 20:17:27.972 [AppCenter] DEBUG: AddChannel(core)
2021-08-18 20:17:28.233 [AppCenter] INFO: App Center SDK configured successfully.
2021-08-18 20:17:28.264 [AppCenter] DEBUG: Set max storage size.
2021-08-18 20:17:28.296 [AppCenter] DEBUG: AddChannel(analytics)
2021-08-18 20:17:28.329 [AppCenter] INFO: Found 577 pages in the database.
2021-08-18 20:17:28.359 [AppCenter] INFO: Changed maximum database size to 10485760 bytes.
2021-08-18 20:17:28.391 [AppCenter] INFO: 'Analytics' service started.
2021-08-18 20:17:28.424 [AppCenter] DEBUG: AddChannel(crashes)
2021-08-18 20:17:28.454 [AppCenter] INFO: 'Crashes' service started.
2021-08-18 20:17:28.489 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'core'
2021-08-18 20:17:31.631 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'core'
2021-08-18 20:17:34.198 [AppCenter] DEBUG: CheckPendingLogs(core) pending log count: 1
2021-08-18 20:17:35.609 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'analytics'
2021-08-18 20:17:35.647 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'analytics'
2021-08-18 20:17:35.853 [AppCenter] DEBUG: CheckPendingLogs(analytics) pending log count: 1
2021-08-18 20:17:36.458 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'analytics'
2021-08-18 20:17:36.488 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'analytics'
2021-08-18 20:17:36.562 [AppCenter] DEBUG: CheckPendingLogs(analytics) pending log count: 2
2021-08-18 20:17:36.601 [AppCenterAnalytics] DEBUG: SessionTracker.Resume
2021-08-18 20:17:36.633 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'analytics'
2021-08-18 20:17:36.663 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'analytics'
2021-08-18 20:17:36.742 [AppCenter] DEBUG: CheckPendingLogs(analytics) pending log count: 3
2021-08-18 20:17:37.393 [AppCenter] DEBUG: TriggerIngestion(core) pending log count: 1
2021-08-18 20:17:37.493 [AppCenter] DEBUG: Trying to get up to 50 logs from storage for core
2021-08-18 20:17:38.295 [AppCenter] DEBUG: The SID/ID pairs for returning logs are:
	(null) / 1176
2021-08-18 20:17:38.308 [AppCenter] DEBUG: Invoke SendingLog event for channel 'core'
2021-08-18 20:17:38.554 [AppCenter] VERBOSE: Calling https://in.appcenter.ms/logs?api-version=1.0.0...
2021-08-18 20:17:38.594 [AppCenter] VERBOSE: Headers: App-Secret=****************************acc060ac, Install-ID=fa1fcd50-e107-45c2-8c75-86686dacca15
2021-08-18 20:17:38.627 [AppCenter] VERBOSE: {
  "logs": [
    {
  "services": [
    "Analytics",
    "Crashes"
  ],
  "timestamp": "2021-08-18T12:17:31.6304595Z",
  "device": {
    "sdkName": "appcenter.uwp",
    "sdkVersion": "4.3.0",
    "model": "HP EliteDesk 800 G5 TWR",
    "oemName": "HP",
    "osName": "WINDOWS",
    "osVersion": "10.0.19042",
    "osBuild": "10.0.19042.985",
    "locale": "en-US",
    "timeZoneOffset": 480,
    "appVersion": "2.14.28.0",
    "appBuild": "2.14.28.0",
    "appNamespace": "36699Atelier39.forWin102"
  },
  "type": "startService"
}
  ]
}
Handling new window size: 1171x932
2021-08-18 20:17:39.157 [AppCenter] DEBUG: TriggerIngestion(analytics) pending log count: 3
2021-08-18 20:17:39.192 [AppCenter] DEBUG: Trying to get up to 50 logs from storage for analytics
2021-08-18 20:17:39.228 [AppCenter] DEBUG: CheckPendingLogs(core) pending log count: 0
2021-08-18 20:17:39.335 [AppCenter] DEBUG: The SID/ID pairs for returning logs are:
	(null) / 1177
	(null) / 1178
	5ed1d909-d97b-4cf1-ab1e-180d2b41cdeb / 1179
2021-08-18 20:17:39.365 [AppCenter] DEBUG: Invoke SendingLog event for channel 'analytics'
2021-08-18 20:17:39.397 [AppCenter] DEBUG: Invoke SendingLog event for channel 'analytics'
2021-08-18 20:17:39.400 [AppCenter] DEBUG: Invoke SendingLog event for channel 'analytics'
2021-08-18 20:17:39.408 [AppCenter] VERBOSE: Calling https://in.appcenter.ms/logs?api-version=1.0.0...
2021-08-18 20:17:39.443 [AppCenter] VERBOSE: Headers: App-Secret=****************************acc060ac, Install-ID=fa1fcd50-e107-45c2-8c75-86686dacca15
2021-08-18 20:17:39.474 [AppCenter] VERBOSE: {
  "logs": [
    {
  "id": "2988fbc3-fafe-4491-99e5-194edc764ea1",
  "name": "app.active.startup.sys",
  "properties": {
    "kind": "app-ctor",
    "pre_state": "app-ctor"
  },
  "timestamp": "2021-08-18T12:17:35.6479866Z",
  "device": {
    "sdkName": "appcenter.uwp",
    "sdkVersion": "4.3.0",
    "model": "HP EliteDesk 800 G5 TWR",
    "oemName": "HP",
    "osName": "WINDOWS",
    "osVersion": "10.0.19042",
    "osBuild": "10.0.19042.985",
    "locale": "en-US",
    "timeZoneOffset": 480,
    "appVersion": "2.14.28.0",
    "appBuild": "2.14.28.0",
    "appNamespace": "36699Atelier39.forWin102"
  },
  "type": "event"
},
    {
  "id": "b5ac740d-364f-4fdb-bbcf-00458e6f7f4d",
  "name": "app.active.startup.sys",
  "properties": {
    "kind": "Launch",
    "pre_state": "Terminated"
  },
  "timestamp": "2021-08-18T12:17:36.4882684Z",
  "device": {
    "sdkName": "appcenter.uwp",
    "sdkVersion": "4.3.0",
    "model": "HP EliteDesk 800 G5 TWR",
    "oemName": "HP",
    "osName": "WINDOWS",
    "osVersion": "10.0.19042",
    "osBuild": "10.0.19042.985",
    "locale": "en-US",
    "timeZoneOffset": 480,
    "appVersion": "2.14.28.0",
    "appBuild": "2.14.28.0",
    "appNamespace": "36699Atelier39.forWin102"
  },
  "type": "event"
},
    {
  "timestamp": "2021-08-18T12:17:36.6634274Z",
  "sid": "5ed1d909-d97b-4cf1-ab1e-180d2b41cdeb",
  "device": {
    "sdkName": "appcenter.uwp",
    "sdkVersion": "4.3.0",
    "model": "HP EliteDesk 800 G5 TWR",
    "oemName": "HP",
    "osName": "WINDOWS",
    "osVersion": "10.0.19042",
    "osBuild": "10.0.19042.985",
    "locale": "en-US",
    "timeZoneOffset": 480,
    "appVersion": "2.14.28.0",
    "appBuild": "2.14.28.0",
    "appNamespace": "36699Atelier39.forWin102"
  },
  "type": "startSession"
}
  ]
}
2021-08-18 20:17:39.505 [AppCenter] DEBUG: CheckPendingLogs(analytics) pending log count: 0

**Comment by AnastasiaKubova** [comment] 2021-08-18 12:32
Is this error crash your app or it just appears in the logs? Based on your new logs I see that App Center works correctly and sends logs. Also, I can't reproduce this issue in my environment. Probably you have some specific configuration of your project about I should know?

**Comment by HppZ** [comment] 2021-08-18 12:33
it just appears in the logs.
I have no idea what is wrong.

**Comment by AnastasiaKubova** [comment] 2021-08-18 13:16
We investigated this issue more and looks like your issue is related to this [PR](https://github.com/microsoft/appcenter-sdk-dotnet/pull/422/files#), where it has already been fixed. If this error doesn't affect your app you should probably ignore it.

**Comment by HppZ** [comment] 2021-08-18 13:44
got you, thanks.

**Comment by AnastasiaKubova** [comment] 2021-08-18 14:12
I’m closing this issue but feel free to reopen it if you have additional questions.
Thanks for using App Center.

**Closed as completed by AnastasiaKubova** 2021-08-18 14:12 UTC
Labels: App Center SDK, Pri2, app-center-general/subsvc, vs-appcenter-sdk/svc
