### ISSUE TITLE
Add testing support for React Native test frameworks

### ISSUE THREAD

**Issue by sators** [MicrosoftDocs/appcenter-docs#992] opened 2020-04-21 13:34 UTC
Detox would be a great add for React Native based projects - https://github.com/wix/Detox

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e1f8239-19fa-9c4b-52f5-b9c19cafbb4a
* Version Independent ID: 1980a317-8a4a-10b3-eedd-32af9d36cfbe
* Content: [Supported Test Frameworks - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/supported-frameworks#feedback)
* Content Source: [docs/test-cloud/supported-frameworks.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/supported-frameworks.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by King-of-Spades** [comment] 2020-04-21 18:43
Duplicate of https://github.com/microsoft/appcenter/issues/262. You can upvote that issue to show your support.

**Closed as completed by King-of-Spades** 2020-04-21 18:43 UTC
Labels: Feature Request, vs-appcenter/svc, Pri2, app-center-test/subsvc
