### ISSUE TITLE
Assemblies Not Strong Named

### ISSUE THREAD

**Issue by jstevenson72** [MicrosoftDocs/appcenter-docs#694] opened 2019-08-28 14:05 UTC
Got excited after watching a YouTube video today.  Tried to put this into my application, but the Microsoft AppCenter assemblies are not strong named, so it cannot be used.

Could not load file or assembly 'Microsoft.AppCenter.Analytics, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

How do you publish a NuGet package, but not sign your assemblies?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e799e45-8feb-d74c-4e25-3bdf49301766
* Version Independent ID: b6aef403-76f7-5df2-aa5d-3ed66397893d
* Content: [Get Started with WPF/WinForms - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/wpf-winforms#feedback)
* Content Source: [docs/sdk/getting-started/wpf-winforms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/wpf-winforms.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by NunoPeixotoPrimavera** [comment] 2019-09-30 14:47
Any response on this?

**Comment by level54** [comment] 2019-10-01 09:29
Yeah, I also got all excited and although AppCentre for WinForms is in Preview, I decided to give it a go.

All I get is:
System.IO.FileLoadException: 'Could not load file or assembly 'Microsoft.AppCenter.Analytics, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

So I guess I'll remove the 416Mb of packages that NuGet added to project to get AppCentre working, and try it again when it is an actual working product.

**Comment by ExtremeKaos** [comment] 2019-10-01 18:27
Yeah, i have one app in wpf working with HockeyApp and try to move to AppCenter... no lucky yet..
45 days for HockeyApp supports ends...

**Comment by rfinizio** [comment] 2019-11-25 17:20
the problem still exists, no signed distribution it is possible

**Comment by anywherepilot** [comment] 2019-12-09 09:02
@NunoPeixotoPrimavera @level54 @ExtremeKaos @rfinizio please upvote the feature request here so we can prioritize it against other requests: microsoft/appcenter#1321

I understand this is an important issue to all of you. Since it is not a documentation issue, I will close this now so the future discussion can all be in one place. Feel free to reopen if you believe there should be a documentation change.

**Closed as completed by anywherepilot** 2019-12-09 09:02 UTC
Labels: vs-appcenter/svc, Pri2

**Comment by obrocki-fortem** [comment] 2020-03-31 12:54
Any update on this one?

**Comment by anywherepilot** [comment] 2020-04-01 02:30
@obrocki-fortem do you believe there is a problem with the documentation of a current feature? If the problem is a missing or broken feature, please use the main repository. My previous comment has a link to an issue there related to this one, where you can track and request updates regarding its process.

**Comment by obrocki-fortem** [comment] 2020-04-01 07:46
> @obrocki-fortem do you believe there is a problem with the documentation of a current feature? If the problem is a missing or broken feature, please use the main repository. My previous comment has a link to an issue there related to this one, where you can track and request updates regarding its process.

@anywherepilot thank you
