### ISSUE TITLE
Anyway to update android ndk-bundle?

### ISSUE THREAD

**Issue by heruoxin** [MicrosoftDocs/appcenter-docs#950] opened 2020-03-06 05:46 UTC
The android ndk-bundle version of build machine is still 18.1.5063045. Is there any way to update it to newer version such as 21.0.6113669?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 022126c7-2d61-9c53-6881-149310c137c0
* Version Independent ID: 4fe62fb4-6dd9-057e-8f57-fb4c6dcb71f8
* Content: [App Center Cloud Build Machines - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/software#feedback)
* Content Source: [docs/build/software.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/software.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-build**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **niloferr**

**Comment by King-of-Spades** [comment] 2020-04-17 17:59
Closing as duplicate of this request: https://github.com/microsoft/appcenter/issues/1740

You can give that issue a 👍 to show your support.

**Closed as completed by King-of-Spades** 2020-04-17 17:59 UTC
Labels: App Center Build, Feature Request, vs-appcenter/svc, Pri2, app-center-build/subsvc

**Comment by Armcannon** [comment] 2021-04-26 05:45
F.R.I.S. Chapter 1 - Hacker ARC 

- [ ] ### 

> `_com.fris.chapter2**[F.R.I.S. Chapter 1 - Hacker ARC](com.fris.chapter2) **_`
