### ISSUE TITLE
How to distribute apps to Android TV using AppCenter

### ISSUE THREAD

**Issue by PawelRutkowskiVIMN** [MicrosoftDocs/appcenter-docs#877] opened 2019-12-31 10:09 UTC
Hi
We are using AppCenter to distribute our apps for Mobile (Android/iOS) and we would like also to use it for Android TV. 
How to do it?
Where to get AppCenter app for Android TV?

BR
Paweł Rutkowski

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40294974-bc6b-45af-f1bd-3bd8187153ac
* Version Independent ID: 21420d35-1e72-a8b8-d587-40b2913120ba
* Content: [App Center Distribute for Android - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#feedback)
* Content Source: [docs/sdk/distribute/android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/distribute/android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by botatoes** [comment] 2020-01-10 05:07
Hi Pawel, we're current doing work to support tvOS. After we are done with that, we will look into Android TV as a platform.

**Comment by King-of-Spades** [comment] 2020-04-17 17:40
Duplicate of https://github.com/microsoft/appcenter/issues/471. I recommend upvoting that with a 👍if you haven't done so already.

**Closed as completed by King-of-Spades** 2020-04-17 17:40 UTC
Labels: App Center Distribution, Feature Request, vs-appcenter/svc, Pri1

**Comment by tgkess1018** [comment] 2022-10-27 23:47
Any updates to this?
